[build-system]
requires = ["setuptools==83.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pystreamliner"
version = "1.21.1"
description = "A conservative, zero-dependency Python source code cleaner"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
]
authors = [
    {name = "Supe232323"}
]

[project.scripts]
pystreamliner = "streamliner:main"

[project.urls]
Homepage = "https://github.com/Supe232323/pystreamliner"
Repository = "https://github.com/Supe232323/pystreamliner"
Issues = "https://github.com/Supe232323/pystreamliner/issues"

[tool.setuptools]
py-modules = ["streamliner"]
